project:
  type: website
  preview:
    port: 4200

website:
  title: Gitcoin Grants Data Portal
  favicon: favicon.ico
  repo-url: https://github.com/davidgasquez/gitcoin-grants-data-portal
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: /data
        text: Data
      - href: about.qmd
        text: About
      - href: catalog.ipynb
        text: Catalog
      - href: dbt
        text: dbt Docs
    tools:
      - icon: twitter
        href: https://twitter.com/davidgasquez
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/davidgasquez/gitcoin-grants-data-portal
          - text: Create an Issue
            url: https://github.com/davidgasquez/gitcoin-grants-data-portal/issues/new
          - text: "Request Dataset"
            href: https://github.com/davidgasquez/filecoin-data-portal/issues/new
format:
  html:
    theme:
      - Lumen
      - styles.scss
